# Generated by Django 5.1.6 on 2025-05-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
