# Generated by Django 5.2 on 2025-04-05 21:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('real_name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
            options={
                'ordering': ['user_name', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a category (e.g., Bread, Quick Bread, Cake)', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name if left blank', max_length=200, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Optional icon for this category', null=True, upload_to='category_icons/')),
                ('color', models.CharField(blank=True, help_text='Optional hex color code (e.g. #ffcc00)', max_length=7)),
                ('category_type', models.CharField(choices=[('main', 'Main Category'), ('sub', 'Subcategory')], default='main', help_text='Main category or subcategory', max_length=10)),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent category if this is a subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField(help_text='Enter the ingredients in quantity + ingredient format, e.g., "4 tbsp sugar".', max_length=1000)),
                ('instructions', models.TextField(help_text='Enter the recipe instructions.', verbose_name='Instructions')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipe_pics/')),
                ('category', models.ManyToManyField(help_text='Select a category for this recipe', to='catalog.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], default=3, help_text='Rating given by the user (1 to 5).')),
                ('comment', models.TextField(blank=True, help_text='Optional comment provided by the user.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(help_text='The recipe being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.recipe')),
                ('user', models.ForeignKey(help_text='The user who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.usertype'),
        ),
    ]
