# Generated by Django 5.1.6 on 2025-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_recipe_rating_recipenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
