# Generated by Django 5.1.6 on 2025-04-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=models.CharField(max_length=100, unique=True), max_length=100, unique=True),
        ),
    ]
