# Generated by Django 5.1.6 on 2025-04-06 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_user_username'),
    ]

    operations = [
    ]
